# Generated by Django 3.2 on 2024-05-05 02:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostdomain',
            name='expire_date',
            field=models.DateField(default=datetime.date(2025, 5, 5)),
        ),
        migrations.AlterField(
            model_name='hostdomain',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 5, 5)),
        ),
        migrations.AlterField(
            model_name='resdomain',
            name='expire_date',
            field=models.DateField(default=datetime.date(2025, 5, 5)),
        ),
        migrations.AlterField(
            model_name='resdomain',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 5, 5)),
        ),
        migrations.AlterField(
            model_name='sharedhosting',
            name='expire_date',
            field=models.DateField(default=datetime.date(2025, 5, 5)),
        ),
        migrations.AlterField(
            model_name='sharedhosting',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 5, 5)),
        ),
        migrations.AlterField(
            model_name='vps',
            name='expire_date',
            field=models.DateField(default=datetime.date(2025, 5, 5)),
        ),
        migrations.AlterField(
            model_name='vps',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 5, 5)),
        ),
    ]
