# Generated by Django 3.1.5 on 2021-03-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='month_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
