# Generated by Django 3.2 on 2024-05-11 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20240505_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostdomain',
            name='expire_date',
            field=models.DateField(default=datetime.date(2025, 5, 11)),
        ),
        migrations.AlterField(
            model_name='hostdomain',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 5, 11)),
        ),
        migrations.AlterField(
            model_name='resdomain',
            name='expire_date',
            field=models.DateField(default=datetime.date(2025, 5, 11)),
        ),
        migrations.AlterField(
            model_name='resdomain',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 5, 11)),
        ),
        migrations.AlterField(
            model_name='sharedhosting',
            name='expire_date',
            field=models.DateField(default=datetime.date(2025, 5, 11)),
        ),
        migrations.AlterField(
            model_name='sharedhosting',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 5, 11)),
        ),
        migrations.AlterField(
            model_name='vps',
            name='expire_date',
            field=models.DateField(default=datetime.date(2025, 5, 11)),
        ),
        migrations.AlterField(
            model_name='vps',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 5, 11)),
        ),
    ]
