# Generated by Django 3.1.5 on 2021-03-27 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_month_fees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='month_fees',
        ),
    ]
