# Generated by Django 3.1.5 on 2021-04-02 12:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210402_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostdomain',
            name='expire_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='hostdomain',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 2, 12, 18, 57, 175061, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='resdomain',
            name='expire_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='resdomain',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 2, 12, 18, 57, 175061, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='sharedhosting',
            name='expire_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='sharedhosting',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 2, 12, 18, 57, 175061, tzinfo=utc), null=True),
        ),
    ]
