# Generated by Django 3.1.5 on 2021-04-04 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20210402_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostdomain',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resdomain',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sharedhosting',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
