# Generated by Django 3.1.5 on 2021-04-11 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0008_auto_20210404_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostdomain',
            name='bill_file',
            field=models.ImageField(null=True, upload_to='bill_files_hostdomain/'),
        ),
        migrations.AddField(
            model_name='resdomain',
            name='bill_file',
            field=models.ImageField(null=True, upload_to='bill_files_resdomain/'),
        ),
        migrations.AddField(
            model_name='sharedhosting',
            name='bill_file',
            field=models.ImageField(null=True, upload_to='bill_files_sharedhosting/'),
        ),
        migrations.CreateModel(
            name='VPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=255)),
                ('operation_system', models.CharField(max_length=255)),
                ('ip_address', models.BooleanField()),
                ('ip_count', models.IntegerField()),
                ('port_numbers', models.CharField(max_length=255)),
                ('data_transfer', models.BooleanField()),
                ('data_backup', models.BooleanField()),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('start_date', models.DateField(null=True)),
                ('expire_date', models.DateField(null=True)),
                ('note', models.TextField(null=True)),
                ('bill_file', models.ImageField(null=True, upload_to='bill_files_sharedhosting/')),
                ('my_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
