# Generated by Django 3.1.5 on 2022-04-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20220310_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resdomain',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resdomain',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resdomain',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vps',
            name='bill_file',
            field=models.ImageField(null=True, upload_to='bill_files_VBShosting/'),
        ),
    ]
