# Generated by Django 3.1.5 on 2022-04-10 22:04

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20220407_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_specification',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
