# Generated by Django 3.1.5 on 2022-04-10 22:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_product_product_specification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_specification',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
