# Generated by Django 3.1.5 on 2022-04-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20220411_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vps',
            name='operation_system',
            field=models.IntegerField(choices=[(0, 'windows'), (1, 'linux')], null=True),
        ),
    ]
