# Generated by Django 3.1.5 on 2022-05-01 21:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20220428_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostdomain',
            name='note',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='resdomain',
            name='note',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sharedhosting',
            name='note',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='vps',
            name='note',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
