# Generated by Django 3.1.5 on 2022-05-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20220502_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='resdomain',
            name='hosting_company',
            field=models.CharField(default='text', max_length=255),
            preserve_default=False,
        ),
    ]
