# Generated by Django 3.1.5 on 2022-05-29 21:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_resdomain_hosting_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
