# Generated by Django 3.1.5 on 2022-06-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_auto_20220530_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostdomain',
            name='domain_name',
            field=models.URLField(unique=True),
        ),
    ]
