# Generated by Django 3.1.5 on 2022-07-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20220605_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vps',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
    ]
