# Generated by Django 3.1.5 on 2022-07-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20220705_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedhosting',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sharedhosting',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vps',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vps',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
