# Generated by Django 3.1.5 on 2022-07-05 17:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_auto_20220705_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedhosting',
            name='note',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vps',
            name='note',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
