# Generated by Django 3.1.5 on 2022-11-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_auto_20220705_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostdomain',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
