# Generated by Django 3.1.5 on 2022-11-18 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_auto_20221118_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostdomain',
            name='expire_date',
            field=models.DateField(default=datetime.date(2023, 11, 18)),
        ),
    ]
