# Generated by Django 3.1.5 on 2022-11-19 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_auto_20221118_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostdomain',
            name='expire_date',
            field=models.DateField(default=datetime.date(2023, 11, 19)),
        ),
        migrations.AlterField(
            model_name='hostdomain',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 11, 19)),
        ),
        migrations.AlterField(
            model_name='resdomain',
            name='activate',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='resdomain',
            name='domain_name',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='resdomain',
            name='expire_date',
            field=models.DateField(default=datetime.date(2023, 11, 19)),
        ),
        migrations.AlterField(
            model_name='resdomain',
            name='hosting_company',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resdomain',
            name='primary_name_server',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resdomain',
            name='secondary_name_server',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resdomain',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 11, 19)),
        ),
        migrations.AlterField(
            model_name='sharedhosting',
            name='backup_website',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sharedhosting',
            name='expire_date',
            field=models.DateField(default=datetime.date(2023, 11, 19)),
        ),
        migrations.AlterField(
            model_name='sharedhosting',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 11, 19)),
        ),
        migrations.AlterField(
            model_name='sharedhosting',
            name='transfer_website',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sharedhosting',
            name='website_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='vps',
            name='data_backup',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vps',
            name='data_transfer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vps',
            name='expire_date',
            field=models.DateField(default=datetime.date(2023, 11, 19)),
        ),
        migrations.AlterField(
            model_name='vps',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='vps',
            name='ip_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vps',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 11, 19)),
        ),
        migrations.AlterField(
            model_name='vps',
            name='website_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
