# Generated by Django 3.2 on 2023-08-02 21:59

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_auto_20221119_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostdomain',
            name='expire_date',
            field=models.DateField(default=datetime.date(2024, 8, 3)),
        ),
        migrations.AlterField(
            model_name='hostdomain',
            name='note',
            field=ckeditor.fields.RichTextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='hostdomain',
            name='start_date',
            field=models.DateField(default=datetime.date(2023, 8, 3)),
        ),
        migrations.AlterField(
            model_name='resdomain',
            name='expire_date',
            field=models.DateField(default=datetime.date(2024, 8, 3)),
        ),
        migrations.AlterField(
            model_name='resdomain',
            name='note',
            field=ckeditor.fields.RichTextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='resdomain',
            name='start_date',
            field=models.DateField(default=datetime.date(2023, 8, 3)),
        ),
        migrations.AlterField(
            model_name='sharedhosting',
            name='expire_date',
            field=models.DateField(default=datetime.date(2024, 8, 3)),
        ),
        migrations.AlterField(
            model_name='sharedhosting',
            name='note',
            field=ckeditor.fields.RichTextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='sharedhosting',
            name='start_date',
            field=models.DateField(default=datetime.date(2023, 8, 3)),
        ),
        migrations.AlterField(
            model_name='vps',
            name='expire_date',
            field=models.DateField(default=datetime.date(2024, 8, 3)),
        ),
        migrations.AlterField(
            model_name='vps',
            name='note',
            field=ckeditor.fields.RichTextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='vps',
            name='start_date',
            field=models.DateField(default=datetime.date(2023, 8, 3)),
        ),
    ]
