# Generated by Django 3.2 on 2023-10-09 22:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_auto_20230804_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedhosting',
            name='product_type',
            field=models.ForeignKey(default='استضافة مشتركة', on_delete=django.db.models.deletion.CASCADE, to='product.type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hostdomain',
            name='expire_date',
            field=models.DateField(default=datetime.date(2024, 10, 10)),
        ),
        migrations.AlterField(
            model_name='hostdomain',
            name='start_date',
            field=models.DateField(default=datetime.date(2023, 10, 10)),
        ),
        migrations.AlterField(
            model_name='resdomain',
            name='expire_date',
            field=models.DateField(default=datetime.date(2024, 10, 10)),
        ),
        migrations.AlterField(
            model_name='resdomain',
            name='start_date',
            field=models.DateField(default=datetime.date(2023, 10, 10)),
        ),
        migrations.AlterField(
            model_name='sharedhosting',
            name='expire_date',
            field=models.DateField(default=datetime.date(2024, 10, 10)),
        ),
        migrations.AlterField(
            model_name='sharedhosting',
            name='my_product',
            field=models.ForeignKey(limit_choices_to={'product_type': 'self.product_type'}, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AlterField(
            model_name='sharedhosting',
            name='start_date',
            field=models.DateField(default=datetime.date(2023, 10, 10)),
        ),
        migrations.AlterField(
            model_name='vps',
            name='expire_date',
            field=models.DateField(default=datetime.date(2024, 10, 10)),
        ),
        migrations.AlterField(
            model_name='vps',
            name='start_date',
            field=models.DateField(default=datetime.date(2023, 10, 10)),
        ),
    ]
