# Generated by Django 3.2 on 2023-10-09 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_auto_20231010_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedhosting',
            name='my_product',
            field=models.ForeignKey(limit_choices_to={'product_type': 'self.product_type.id'}, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
