# Generated by Django 3.2 on 2023-10-09 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_alter_sharedhosting_my_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedhosting',
            name='my_product',
            field=models.ForeignKey(limit_choices_to=models.Q(product_type=None), on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
