# Generated by Django 3.2 on 2023-10-09 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_alter_sharedhosting_my_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedhosting',
            name='product_type',
        ),
        migrations.AlterField(
            model_name='sharedhosting',
            name='my_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
