# Generated by Django 3.2 on 2023-10-10 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_auto_20231010_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedhosting',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.type'),
        ),
    ]
