# Generated by Django 3.2 on 2023-12-04 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0040_auto_20231024_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostdomain',
            name='expire_date',
            field=models.DateField(default=datetime.date(2024, 12, 4)),
        ),
        migrations.AlterField(
            model_name='hostdomain',
            name='start_date',
            field=models.DateField(default=datetime.date(2023, 12, 4)),
        ),
        migrations.AlterField(
            model_name='resdomain',
            name='expire_date',
            field=models.DateField(default=datetime.date(2024, 12, 4)),
        ),
        migrations.AlterField(
            model_name='resdomain',
            name='start_date',
            field=models.DateField(default=datetime.date(2023, 12, 4)),
        ),
        migrations.AlterField(
            model_name='sharedhosting',
            name='expire_date',
            field=models.DateField(default=datetime.date(2024, 12, 4)),
        ),
        migrations.AlterField(
            model_name='sharedhosting',
            name='start_date',
            field=models.DateField(default=datetime.date(2023, 12, 4)),
        ),
        migrations.AlterField(
            model_name='vps',
            name='expire_date',
            field=models.DateField(default=datetime.date(2024, 12, 4)),
        ),
        migrations.AlterField(
            model_name='vps',
            name='start_date',
            field=models.DateField(default=datetime.date(2023, 12, 4)),
        ),
    ]
