# Generated by Django 3.1.5 on 2021-02-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_auto_20210215_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fbName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telegram',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
