# Generated by Django 3.1.5 on 2021-03-27 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0004_auto_20210223_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproduct',
            name='expire_date',
            field=models.DateField(default=datetime.date(2022, 3, 27)),
        ),
        migrations.AlterField(
            model_name='myproduct',
            name='start_date',
            field=models.DateField(default=datetime.date(2021, 3, 27)),
        ),
    ]
