# Generated by Django 3.1.5 on 2021-03-27 21:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0005_auto_20210327_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproduct',
            name='expire_date',
            field=models.DateField(default=datetime.date(2022, 3, 28)),
        ),
        migrations.AlterField(
            model_name='myproduct',
            name='start_date',
            field=models.DateField(default=datetime.date(2021, 3, 28)),
        ),
    ]
