# Generated by Django 3.1.5 on 2021-03-29 10:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0006_auto_20210328_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproduct',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myproduct',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='myproduct',
            name='expire_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 29, 10, 26, 38, 250493, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='myproduct',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 29, 10, 26, 38, 250493, tzinfo=utc)),
        ),
    ]
