# Generated by Django 3.1.5 on 2021-04-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0009_auto_20210404_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='customer_type',
            field=models.IntegerField(choices=[(0, 'مؤسسة حكومية مالية'), (1, 'مؤسسة حكومية إدارية'), (2, 'مؤسسة خاصة')], null=True),
        ),
    ]
