# Generated by Django 3.1.5 on 2021-04-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0010_companyprofile_customer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='phone',
            field=models.CharField(default='+963', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='finanicalresponse',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='finanicalresponse',
            name='financial_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='finanicalresponse',
            name='phone',
            field=models.CharField(default='+963', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='technicalresponse',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='technicalresponse',
            name='phone',
            field=models.CharField(default='+963', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='technicalresponse',
            name='technical_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
