# Generated by Django 3.1.5 on 2022-03-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0011_auto_20210405_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='phone',
            field=models.CharField(default='+963', max_length=12, null=True),
        ),
    ]
