# Generated by Django 3.1.5 on 2022-03-10 08:58

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0012_auto_20220310_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default=0, max_length=128, region=None),
        ),
    ]
