# Generated by Django 3.1.5 on 2022-05-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0014_auto_20220310_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='customer_type',
            field=models.IntegerField(choices=[(0, 'مؤسسة حكومية مالية'), (1, 'مؤسسة حكومية إدارية'), (2, 'مؤسسة خاصة')], default=2, null=True),
        ),
    ]
