# Generated by Django 3.1.5 on 2022-06-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0015_auto_20220519_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fbName',
            new_name='facebook',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
