# Generated by Django 3.1.5 on 2022-07-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0016_auto_20220604_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='facebook',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telegram',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
