# Generated by Django 3.1.5 on 2022-08-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0018_auto_20220718_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='botpress',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
