# Generated by Django 3.2 on 2023-08-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0019_profile_botpress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', null=True, upload_to='profile_Img/'),
        ),
    ]
