# Generated by Django 3.2 on 2023-12-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0020_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=25, null=True),
        ),
    ]
