# Generated by Django 3.2 on 2023-12-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0021_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='customer_type',
            field=models.CharField(choices=[('gov_fin', 'مؤسسة حكومية مالية'), ('gov_man', 'مؤسسة حكومية إدارية'), ('special', 'مؤسسة خاصة')], default=2, max_length=15, null=True),
        ),
    ]
