# Generated by Django 3.2 on 2023-08-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Botpress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('botpress_base_url', models.TextField()),
                ('db_url', models.TextField()),
                ('db_type', models.CharField(choices=[('postgresql', 'post'), ('sqlite', 'sqlite')], default='sqlite', max_length=15)),
                ('db_username', models.TextField()),
                ('db_password', models.TextField()),
            ],
        ),
    ]
