# Generated by Django 3.2 on 2024-01-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Botpress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('botpress_base_url', models.URLField(null=True)),
                ('db_url', models.CharField(max_length=200, null=True)),
                ('db_type', models.CharField(choices=[('postgresql', 'postgresql'), ('sqlite', 'sqlite')], default='sqlite', max_length=15)),
                ('db_name', models.CharField(max_length=200, null=True)),
                ('db_username', models.CharField(max_length=200, null=True)),
                ('db_password', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
