# Generated by Django 3.2 on 2023-08-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botpress',
            name='botpress_base_url',
            field=models.URLField(),
        ),
    ]
