# Generated by Django 3.2 on 2023-08-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_alter_botpress_botpress_base_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='botpress',
            name='db_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='botpress',
            name='botpress_base_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='botpress',
            name='db_password',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='botpress',
            name='db_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='botpress',
            name='db_username',
            field=models.TextField(null=True),
        ),
    ]
