# Generated by Django 3.2 on 2023-08-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_auto_20230803_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botpress',
            name='db_name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='botpress',
            name='db_password',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='botpress',
            name='db_type',
            field=models.CharField(choices=[('postgresql', 'postgresql'), ('sqlite', 'sqlite')], default='sqlite', max_length=15),
        ),
        migrations.AlterField(
            model_name='botpress',
            name='db_url',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='botpress',
            name='db_username',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
