# Generated by Django 3.2 on 2023-08-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_auto_20230804_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botpress',
            name='db_password',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='botpress',
            name='db_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='botpress',
            name='db_username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
