# Generated by Django 3.2 on 2023-08-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_auto_20230804_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botpress',
            name='db_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
