# Generated by Django 3.2 on 2024-01-19 21:29

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('data_type', models.CharField(choices=[('pdf', 'PDF file'), ('web', 'Website Page')], max_length=50)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('translate', models.TextField(blank=True, null=True)),
                ('translated', models.BooleanField(default=False, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('knowledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa_model.dataurl')),
            ],
        ),
    ]
