# Generated by Django 3.2 on 2024-01-20 21:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='ar_embeddings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=768),
        ),
        migrations.AddField(
            model_name='passage',
            name='en_embeddings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=768),
        ),
    ]
