# Generated by Django 3.2 on 2023-10-20 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('data_type', models.CharField(choices=[('pdf', 'PDF file'), ('web', 'Website Page')], max_length=50)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PDFile',
        ),
        migrations.DeleteModel(
            name='WebsiteURL',
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='qa_model.dataurl', null=True),
            preserve_default=False,
        ),
    ]
