# Generated by Django 3.2 on 2023-10-20 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa_model', '0002_auto_20231020_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebase',
            name='data',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='qa_model.dataurl'),
        ),
    ]
