# Generated by Django 3.2 on 2024-01-21 19:53

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('qa_model', '0002_auto_20240121_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='ar_pg_embeddings',
            field=pgvector.django.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
