# Generated by Django 3.2 on 2023-10-24 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa_model', '0003_alter_knowledgebase_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebase',
            name='data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='qa_model.dataurl'),
        ),
    ]
