# Generated by Django 3.2 on 2024-01-21 21:42

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('qa_model', '0003_passage_ar_pg_embeddings'),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='en_pg_embeddings',
            field=pgvector.django.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
