# Generated by Django 3.2 on 2024-03-31 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_model', '0004_passage_en_pg_embeddings'),
    ]

    operations = [
        migrations.CreateModel(
            name='QA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('passages', models.ManyToManyField(to='qa_model.Passage')),
            ],
        ),
    ]
