# Generated by Django 3.2 on 2024-01-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_model', '0005_passage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgebase',
            name='file',
        ),
        migrations.AddField(
            model_name='passage',
            name='translated',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
