# Generated by Django 3.2 on 2024-03-31 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_model', '0005_qa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa',
            name='passages',
            field=models.ManyToManyField(blank=True, null=True, to='qa_model.Passage'),
        ),
    ]
