# Generated by Django 3.2 on 2024-01-16 21:35

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa_model', '0006_auto_20240115_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataurl',
            name='text',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='knowledge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa_model.dataurl'),
        ),
        migrations.DeleteModel(
            name='KnowledgeBase',
        ),
    ]
