# Generated by Django 3.2 on 2024-05-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_model', '0007_auto_20240505_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='qa',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
