# Generated by Django 3.2 on 2024-01-16 21:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa_model', '0007_auto_20240117_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataurl',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
