# Generated by Django 3.2 on 2024-01-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_model', '0008_alter_dataurl_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataurl',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
