# Generated by Django 3.2 on 2024-05-11 09:17

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('qa_model', '0008_qa_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='qa',
            name='ar_q_embeddings',
            field=pgvector.django.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
